In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import linalg
import csv
%matplotlib inline

In [2]:
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 9]])
labels = np.array([0, 1, 2, 0, 1, 2, 0])

In [3]:
# label == 0の値を抽出
X[labels == 0, :]

array([[1, 2],
       [4, 5],
       [7, 9]])

In [4]:
# label == 0の平均値を計算する
X[labels == 0, :].mean(axis=0)

array([4.        , 5.33333333])

In [5]:
cluster_centers = np.array([[1, 1], [2, 2], [3, 3]])

In [15]:
X[:, :, np.newaxis]

array([[[1],
        [2]],

       [[2],
        [3]],

       [[3],
        [4]],

       [[4],
        [5]],

       [[5],
        [6]],

       [[6],
        [7]],

       [[7],
        [9]]])

In [16]:
cluster_centers.T[np.newaxis, :, :]

array([[[1, 2, 3],
        [1, 2, 3]]])

In [13]:
((X[:, :, np.newaxis] - cluster_centers.T[np.newaxis, :, :])**2)

array([[[ 0,  1,  4],
        [ 1,  0,  1]],

       [[ 1,  0,  1],
        [ 4,  1,  0]],

       [[ 4,  1,  0],
        [ 9,  4,  1]],

       [[ 9,  4,  1],
        [16,  9,  4]],

       [[16,  9,  4],
        [25, 16,  9]],

       [[25, 16,  9],
        [36, 25, 16]],

       [[36, 25, 16],
        [64, 49, 36]]])

In [14]:
((X[:, :, np.newaxis] - cluster_centers.T[np.newaxis, :, :])**2).sum(axis=1)

array([[  1,   1,   5],
       [  5,   1,   1],
       [ 13,   5,   1],
       [ 25,  13,   5],
       [ 41,  25,  13],
       [ 61,  41,  25],
       [100,  74,  52]])

In [19]:
p = X[:, :, np.newaxis]
q = cluster_centers.T[np.newaxis, :, :]
r = (p - q)**2
s = r.sum(axis=1)

In [20]:
# 1番近いクラスターを計算
s.argmin(axis=1)

array([0, 1, 2, 2, 2, 2, 2])

In [21]:
X.shape[0]

7

In [ ]:
class KMeans:
    def __init__(self, n_clusters, max_iter=1000, random_seed=0):
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.random_state = np.random.RandomState(random_seed)
        
    def fit(self, X):
        # n_clustersのリスト内を無限繰返する
        cycle = itertools.cycle(range(self.n_clusters))
        # itertools.isliceでcycleをXの１次元の数(X.shape[0])分だけnp.fromiterを使ってnumpyリストとして返す
        self.labels_ = np.fromiter(itetools.islice(cycle, X.shape[0]), dtype=np.int)
        # 
        self.random_state.shuffle(self.labels_)
        #
        labels_prev = np.zeros(X.shape[0])
        count = 0
        #
        self.cluster_centers_ = np.zeros((self.n_clusters, X.shape[1]))
        while 